 aipyqubit: conexapi_backend on main [ conexapi_backend 3.11.9] ❯ alembic revision --autogenerate -m "create erp_config table"
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\aipyqubit\proyectos\conexapi\conexapi_backend\venv\Scripts\alembic.exe\__main__.py", line 7, in <module>
  File "C:\Users\aipyqubit\proyectos\conexapi\conexapi_backend\venv\Lib\site-packages\alembic\config.py", line 641, in main
    CommandLine(prog=prog).main(argv=argv)
  File "C:\Users\aipyqubit\proyectos\conexapi\conexapi_backend\venv\Lib\site-packages\alembic\config.py", line 631, in main
    self.run_cmd(cfg, options)
  File "C:\Users\aipyqubit\proyectos\conexapi\conexapi_backend\venv\Lib\site-packages\alembic\config.py", line 608, in run_cmd
    fn(
  File "C:\Users\aipyqubit\proyectos\conexapi\conexapi_backend\venv\Lib\site-packages\alembic\command.py", line 236, in revision
    script_directory.run_env()
  File "C:\Users\aipyqubit\proyectos\conexapi\conexapi_backend\venv\Lib\site-packages\alembic\script\base.py", line 583, in run_env
    util.load_python_file(self.dir, "env.py")
  File "C:\Users\aipyqubit\proyectos\conexapi\conexapi_backend\venv\Lib\site-packages\alembic\util\pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aipyqubit\proyectos\conexapi\conexapi_backend\venv\Lib\site-packages\alembic\util\pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\aipyqubit\proyectos\conexapi\conexapi_backend\app/db/migrations\env.py", line 20, in <module>
    from app.core.config import settings
  File "C:\Users\aipyqubit\proyectos\conexapi\conexapi_backend\app\core\config.py", line 23, in <module>
    settings = Settings()# type: ignore
               ^^^^^^^^^^
  File "C:\Users\aipyqubit\proyectos\conexapi\conexapi_backend\venv\Lib\site-packages\pydantic_settings\main.py", line 71, in __init__
    super().__init__(
  File "C:\Users\aipyqubit\proyectos\conexapi\conexapi_backend\venv\Lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 4 validation errors for Settings
db_host
  Field required [type=missing, input_value={'database_url': 'mysql+a..._key': 'server-key.pem'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
db_user
  Field required [type=missing, input_value={'database_url': 'mysql+a..._key': 'server-key.pem'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
db_password
  Field required [type=missing, input_value={'database_url': 'mysql+a..._key': 'server-key.pem'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
db_name
  Field required [type=missing, input_value={'database_url': 'mysql+a..._key': 'server-key.pem'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
 aipyqubit: conexapi_backend on main [ conexapi_backend 3.11.9] ❯